set_project("VCX-Labs")
set_version("2.0.0")
set_xmakever("2.6.9")
set_languages("cxx20")

add_rules("mode.debug", "mode.release", "mode.profile")
add_cxxflags("/utf-8")

add_requires("glad")
add_requires("glfw")
add_requires("glm 1.0.0")
add_requires("imgui 1.90.1")
add_requires("spdlog")
add_requires("stb")
add_requires("fmt")
add_requires("tinyobjloader")
add_requires("yaml-cpp")
add_requires("eigen")
add_requires("pybind11", {configs = {python = "python3"}})


if is_plat("macosx") then
    add_defines("PLATFORM_MACOSX")
end

target("assets")
    set_kind("phony")
    set_default(true)
    after_build(function (target)
        os.mkdir(path.join(target:targetdir(), "assets"))
        os.cp("assets/*|shaders", path.join(target:targetdir(), "assets"))
        os.mkdir(path.join(target:targetdir(), "assets", "shaders"))
        os.cp("assets/shaders/*", path.join(target:targetdir(), "assets", "shaders"))
    end)
    after_install(function (target)
        os.mkdir(path.join(target:installdir(), "assets"))
        os.cp("assets/*|shaders", path.join(target:installdir(), "assets"))
        os.mkdir(path.join(target:installdir(), "assets", "shaders"))
        os.cp("assets/shaders/*", path.join(target:installdir(), "assets", "shaders"))
    end)
    after_clean(function (target)
        os.rm(path.join(target:targetdir(), "assets"))
    end)

target("engine")
    set_kind("static")
    add_packages("glad"         , { public = true })
    add_packages("glfw"         , { public = true })
    add_packages("glm"          , { public = true })
    add_packages("imgui"        , { public = true })
    add_packages("spdlog"       , { public = true })
    add_packages("stb"          , { public = true })
    add_packages("fmt"          , { public = true })
    add_packages("tinyobjloader", { public = true })
    add_packages("yaml-cpp"     , { public = true })
    add_packages("pybind11"     , { public = true })
    
    -- Python 配置（尝试从环境变量自动检测，如果失败则使用默认路径）
    on_load(function (target)
        local conda_prefix = os.getenv("CONDA_PREFIX")
        if conda_prefix then
            print("Using conda environment: " .. conda_prefix)
            target:add("includedirs", path.join(conda_prefix, "include/python3.9"), { public = true })
            target:add("linkdirs", path.join(conda_prefix, "lib"), { public = true })
            target:add("rpathdirs", path.join(conda_prefix, "lib"))
        else
            print("CONDA_PREFIX not set, using default path")
            target:add("includedirs", "/home/kylin/miniconda3/envs/subspace_env_clean/include/python3.9", { public = true })
            target:add("linkdirs", "/home/kylin/miniconda3/envs/subspace_env_clean/lib", { public = true })
            target:add("rpathdirs", "/home/kylin/miniconda3/envs/subspace_env_clean/lib")
        end
        target:add("links", "python3.9", { public = true })
    end)

    add_includedirs("src/3rdparty", { public = true })
    add_includedirs("src/VCX"     , { public = true })
    add_headerfiles("src/3rdparty/**.h")
    add_headerfiles("src/3rdparty/**.hpp")
    add_files      ("src/3rdparty/**.cpp")
    add_headerfiles("src/VCX/Assets/**.h")
    add_headerfiles("src/VCX/Assets/**.hpp")
    add_headerfiles("src/VCX/Engine/**.h")
    add_headerfiles("src/VCX/Engine/**.hpp")
    add_files      ("src/VCX/Engine/**.cpp")

target("lab-common")
    set_kind("static")
    add_deps("engine")
    add_deps("assets")
    add_headerfiles("src/VCX/Labs/Common/*.h")
    add_files      ("src/VCX/Labs/Common/*.cpp")

target("NeuralPhysicsSubspaces")
    set_kind("binary")
    add_deps("lab-common")
    add_packages("eigen")
    set_rundir(os.projectdir()) 
    add_headerfiles("src/VCX/Labs/Core/*.h")
    add_headerfiles("src/VCX/Labs/Core/*.hpp")
    add_files      ("src/VCX/Labs/Core/*.cpp")